name: RainbowArmor
main: com.electro2560.dev.RainbowArmor.RainbowArmor
version: 1.5.0
author: ElectroBoy2560
description: >
             Leather armor that changes color like a rainbow!
commands:
  RainbowArmor:
    aliases: [ra]
    description: Main command for rainbow armor.
  